[project]
name = "cxalio-studio-tools"
version = "0.5.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cx-studio","cx-wealth",
    "rich>=14.0.0",
    "ulid-py>=1.1.0",
]

[project.scripts]
mediakiller = "media_killer:run"
mediascout = "media_scout:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["cx_tools_common", "media_killer", "media_scout"]
