[project]
name = "cxalio-studio-tools"
version = "0.5.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cx-studio",
    "rich>=14.0.0",
]

[project.scripts]
mediakiller = "mediakiller:run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["mediakiller"]
