"""脚本生成器。

将 Mission 列表编译为 batch/shell 脚本，脚本直接使用 Mission 最终目标文件名，
不体现临时文件机制。输出格式按平台选择 .bat/.sh。
"""

import sys
from collections.abc import Iterable
from pathlib import Path

from ..media import Mission, iter_option_tokens
from cx_studio.text.shell_escape import join_args


class ScriptMaker:
    """脚本生成器。

    将 Mission 列表转换为可执行的 batch 或 shell 脚本。
    """

    def __init__(self, missions: Iterable[Mission]) -> None:
        """初始化脚本生成器。

        Args:
            missions: Mission 列表
        """
        self._missions = list(missions)

    def save(self, path: Path) -> None:
        """保存脚本到文件。

        根据文件扩展名判断格式：``.bat``/``.cmd`` → Batch，``.sh`` → Shell。
        若未指定扩展名，根据当前平台决定：Windows → ``.bat``，Unix → ``.sh``。

        Args:
            path: 脚本文件路径
        """
        path = Path(path)

        if path.suffix == "":
            default_suffix = ".bat" if sys.platform == "win32" else ".sh"
            path = path.with_suffix(default_suffix)

        if path.suffix.lower() in {".bat", ".cmd"}:
            content = self._generate_batch()
        else:
            content = self._generate_shell()

        path.write_text(content, encoding="utf-8")

        if path.suffix.lower() == ".sh":
            path.chmod(0o755)

    # ------------------------------------------------------------------
    # 内部方法
    # ------------------------------------------------------------------

    def _generate_batch(self) -> str:
        """生成 Batch 脚本内容。"""
        lines: list[str] = [
            "@echo off",
            "chcp 65001 >nul",
            "REM Generated by MediaKiller",
            "",
        ]

        for mission in self._missions:
            cmd = self._build_ffmpeg_command(mission, is_batch=True)
            target_name = mission.standard_target.name
            lines.append(cmd)
            lines.append("if errorlevel 1 (")
            lines.append(f"    echo Failed: {target_name}")
            lines.append(") else (")
            lines.append(f"    echo Success: {target_name}")
            lines.append(")")
            lines.append("")

        return "\n".join(lines)

    def _generate_shell(self) -> str:
        """生成 Shell 脚本内容。"""
        lines: list[str] = [
            "#!/bin/bash",
            "# Generated by MediaKiller",
            "",
        ]

        for mission in self._missions:
            cmd = self._build_ffmpeg_command(mission, is_batch=False)
            target_name = mission.standard_target.name
            lines.append(cmd)
            lines.append("if [ $? -eq 0 ]; then")
            lines.append(f'    echo "Success: {target_name}"')
            lines.append("else")
            lines.append(f'    echo "Failed: {target_name}"')
            lines.append("fi")
            lines.append("")

        return "\n".join(lines)

    def _build_ffmpeg_command(self, mission: Mission, *, is_batch: bool) -> str:
        """构建单条 ffmpeg 命令字符串。

        使用 Mission 的最终目标文件路径（``outputs`` 中的原始路径），
        而非临时文件路径。

        Args:
            mission: 转码任务
            is_batch: 是否为 Batch 格式（影响转义策略）
        """
        args: list[str] = [mission.ffmpeg]

        # 全局 options（不含 -y/-n，由 Mission.__post_init__ 滤除）
        args.extend(iter_option_tokens(mission.options))

        # 覆盖标志（脚本直接操作目标文件，必须明确策略）
        args.append("-y" if mission.overwrite else "-n")

        # 输入文件组
        for input_spec in mission.inputs:
            args.extend(iter_option_tokens(input_spec.options))
            args.extend(["-i", str(input_spec.filename)])

        # 输出文件组（使用最终目标路径）
        for output_spec in mission.outputs:
            args.extend(iter_option_tokens(output_spec.options))
            args.append(str(output_spec.filename))

        return join_args(args, batch=is_batch)
