[project]
name = "cx-studio"
version = "0.1.0"
description = "A Python library for interacting with the CX Studio API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chardet>=5.2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

